services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=magicpost'
      - 'MYSQL_PASSWORD=12345'
      - 'MYSQL_ROOT_PASSWORD=H27u07y03@'
      - 'MYSQL_USER=magicpost'
    ports:
      - '3306'
