services:
  db:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=magicpost'
      - 'POSTGRES_PASSWORD=12345'
      - 'POSTGRES_USER=magicpost'
    ports:
      - '5432'
    volumes:
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql