spring:
  datasource:
    driverClassName: org.postgresql.Driver
    initialization-mode: always
  url: jdbc:postgresql://localhost:5432/magicpost
  username: magicpost
  password: 12345
  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    show-sql: true