spring:
  datasource:
    driverClassName: org.postgresql.Driver
    initialization-mode: always
  url: jdbc:postgresql://localhost:5432/magicpost
  username: magicpost
  password: 12345
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    generate-ddl: true
    properties:
      hibernate.format_sql: true
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
jwt:
  expirationMs: 8400000
